<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            '42102RM',
            'A.H.P. TRAILER',
            'ABOBOYAA',
            'ABSON',
            'ACCES',
            'ACERBI',
            'ACIM',
            'ACTION MOTOR 50',
            'ACTM',
            'ACURA',
            'ADC',
            'ADIGE',
            'ADLY',
            'ADO SOLUTION',
            'AFRIMAS-50',
            'AGRIMAT',
            'AGRIP',
            'AGROMASTER',
            'AHP',
            'AIR PLANE',
            'AJAX',
            'AJUICO',
            'ALFA ROMEO',
            'AMBK',
            'AMICO',
            'ANKAI',
            'APACHE',
            'APOLO',
            'APRILIA',
            'APSONIC',
            'APSONIC X1',
            'ARCTIC CAT',
            'ARILLE',
            'ARO',
            'ASCA',
            'ASHOK LEYLAND',
            'ASIA',
            'ASPONIC',
            'ASTEL GARDEN',
            'ASTIA',
            'ATCOMEX',
            'ATCOTEX',
            'ATLAS',
            'AUDI',
            'AUSSA',
            'AUSTIN',
            'AVIA',
            'AZONIC FLECHE',
            'B.M.K.',
            'BAIC',
            'BAJ ET FOND',
            'BALAY',
            'BAMAKERE',
            'BAO KONIA',
            'BAO-CFC',
            'BAODIAO',
            'BAODJIN',
            'BAOFKF',
            'BAOTIAN',
            'BAOTISS N1',
            'BARBER GREENE',
            'BARNEOUD',
            'BARTH',
            'BARTOLETTI',
            'BASHAN',
            'BATTAGLINO',
            'BAUEMCH',
            'BAUMACH',
            'BAW',
            'BAYUN',
            'BECCAN',
            'BEDFORD',
            'BELL',
            'BENALU',
            'BENNE',
            'BENTLEY',
            'BERCO',
            'BERLIER',
            'BERLVET',
            'BERTOJA',
            'BESTA',
            'BETA',
            'BETONN',
            'BETTERS',
            'BFG',
            'BIMOTA',
            'BISAN DJARA',
            'BITELI',
            'BLUMHARBT',
            'BMW',
            'BOBCAT',
            'BOEFELLER',
            'BOMAG',
            'BOMAG ROCLER',
            'BOMBO',
            'BONSONIC',
            'BOSS',
            'BOWELL',
            'BOXER',
            'BOXER BM',
            'BRIMONT',
            'BSL',
            'BUICK',
            'BUISCAR',
            'BULL',
            'BURG',
            'BUS',
            'BWM',
            'BXL',
            'BY SEA',
            'BYD',
            'BYDFE',
            'C.I.F',
            'CACOMIAF',
            'CADILLAC',
            'CADY',
            'CAGIVA',
            'CAGVA',
            'CAMAA',
            'CAMC',
            'CAMICO',
            'CAMPILLO',
            'CANTER',
            'CANTONS',
            'CANTOUS',
            'CAR',
            'CARDY',
            'CARENZY',
            'CARLSBERG',
            'CARNEHL',
            'CARROSSE',
            'CASE',
            'CASE MACH',
            'CASENAVE',
            'CASTERA',
            'CAT',
            'CATER',
            'CATERPILAR',
            'CAZAUBAN',
            'CBT',
            'CHAN JIA',
            'CHANA',
            'CHANG CHENG',
            'CHANGAN',
            'CHARIOT MANITOU',
            'CHARIOT STAKER',
            'CHEROKEE',
            'CHERY',
            'CHEVROLET',
            'CHINA SINOTRUCQ H.T.',
            'CHINA THT',
            'CHNZHOU',
            'CHRYSLER',
            'CIMC',
            'CITERNE',
            'CITROEN',
            'CITYFOX',
            'CLAAS',
            'CLARK',
            'CLINKER',
            'COBRA',
            'COCICAM',
            'CODER',
            'CODEV',
            'COLES',
            'COMETRA',
            'COMETTO',
            'COMPACTEUR',
            'COMPACTEUR VIBRIANT',
            'CONTINENTAL',
            'CRYPTON',
            'CSCI',
            'DACIA',
            'DACLYM',
            'DAELIM',
            'DAEWOO',
            'DAF',
            'DAIHATSU',
            'DAIMLER',
            'DAKOTA',
            'DALIAN',
            'DAMPER',
            'DATSUN',
            'DAYANG HARLEY',
            'DAYUN',
            'DBOOSE',
            'DE FILIPPI',
            'DELTA',
            'DELTA LVF',
            'DELTA LVS',
            'DEMAG',
            'DEMICO',
            'DEMPER',
            'DENIS SOMAIN',
            'DENKO',
            'DERBI',
            'DEROULEUSE',
            'DEUTSCH',
            'DEUTZ',
            'DEVES',
            'DFAC',
            'DIBEX',
            'DIEBOLT',
            'DIELT',
            'DIHAO',
            'DJAKARTA LINGYANG',
            'DJAKARTA-NINGYANG',
            'DJARA',
            'DOCKER - JIALING',
            'DODGE',
            'DOLCE',
            'DONG FENG',
            'DOOSAN',
            'DORSEY',
            'DORSO',
            'DRAGON',
            'DUCATI',
            'DULEVO',
            'DURA',
            'DYNAPAC',
            'DYNAWEL',
            'EAGER',
            'EBRO',
            'ECHER',
            'EICHER',
            'ELEFANT',
            'ELEVADORA',
            'ELEVATEUR FOURCHE',
            'ELEVATEUR SOUTE',
            'ENGIN',
            'EPANDEUR',
            'ERF',
            'ERKA',
            'ESCALADA',
            'ESCORT',
            'ETOILE',
            'ETRANGER',
            'EVAME',
            'EX.SNM',
            'EXPRESSE',
            'FABRICATION LOCALE',
            'FABRIC-LOC',
            'FABRISEN',
            'FADIYA',
            'FAHMOS',
            'FARDIER',
            'FARMTRAC 80',
            'FASSA',
            'FASSO N 1',
            'FAUN',
            'FAW',
            'FDMCO',
            'FENCO',
            'FENWICK',
            'FERGUSSON',
            'FERRARI',
            'FHIFENG',
            'FIAT',
            'FIDEMCO',
            'FILLIAT',
            'FIRST',
            'FIVER',
            'FLANDRIA',
            'FMC',
            'FONTANA',
            'FORCE',
            'FORD',
            'FORKLIFT',
            'FORLAND',
            'FORSTHER',
            'FORZA',
            'FOSTHERE',
            'FOSTI',
            'FOTON',
            'FOURCHETTE',
            'FRACASSI',
            'FRANCHIN',
            'FREIGHTLINER',
            'FREJAT',
            'FRTN',
            'FRUCTUS',
            'FRUEHAUF',
            'FRUHEAUF',
            'FSO',
            'FUDI',
            'FUTONG 50',
            'FUWA',
            'GAC',
            'GALAXY',
            'GANTOUS',
            'GARDER',
            'GARENZI',
            'GEELY',
            'GENESIS',
            'GEO',
            'GHONTOUS',
            'GIFFORD',
            'GILBERNE',
            'GILBERT',
            'GILERA',
            'GIO',
            'GMC',
            'GOFL',
            'GOL PLUS',
            'GOLDEN-DRAGON',
            'GONDOLA',
            'GOODSENSE',
            'GRADER CAT 120G',
            'GRADER CHANGLIN',
            'GRAND TIGER',
            'GREAT WALL',
            'GREAT WALL MOTORS',
            'GREGORY',
            'GROENEWEGEN',
            'GROSENEWEGEN',
            'GROVE',
            'GRUE KH100',
            'GSC',
            'GUANG DONG',
            'H 40D',
            'H 45D',
            'HABILE LANTIC',
            'HADJIN',
            'HALLA',
            'HAMER',
            'HAMMAR',
            'HANNOMAG',
            'HANSHE',
            'HAODJIN',
            'HAODJIN ZENTESS',
            'HAODJIN ZONTESS',
            'HAOJIAN',
            'HAOJIANG',
            'HAOJIN',
            'HAOJUE',
            'HARLAN',
            'HARLEY DAVIDSON',
            'HAULOTTE',
            'HAWTAI',
            'HDT',
            'HENDRICKS',
            'HERO',
            'HERO MOTO',
            'HEROKONIA',
            'HERO-KONIA',
            'HEULIEZ',
            'HEULIEZ BUS',
            'HEYWANG',
            'HICHER',
            'HINO',
            'HITACHI',
            'HOJBERG D',
            'HONDA',
            'HONDJOU',
            'HONGYA',
            'HORIZON',
            'HOTCHKISS',
            'HOUDON',
            'HOVARYU',
            'HOWO',
            'HUANGHE',
            'HUANJUN',
            'HUMMER',
            'HUSQVARNA',
            'HUWER SPECIAL',
            'HVANCHE',
            'HYOSUG-MASTAR',
            'HYOSUNG',
            'HYSTER',
            'HYUNDAI',
            'IFOR',
            'INDOX',
            'INFINITI',
            'INPTRUCK',
            'INTERNATIONAL',
            'ISC',
            'ISD',
            'ISUZU',
            'ITEC',
            'IVAN',
            'IVECO',
            'JAC',
            'JAGUAR',
            'JAKARTA',
            'JAYT',
            'JC',
            'JCB',
            'JEEP',
            'JIALING',
            'JIAMSSIN',
            'JIANFHE',
            'JIANSHE',
            'JICHEN',
            'JINBEI',
            'JINCHENG',
            'JINEPIN',
            'JINSHE',
            'JJANSH',
            'JMC',
            'JOCQ J5 REM',
            'JOCQUIN',
            'JOG',
            'JOHN',
            'JOHN DERE',
            'JS110-3',
            'JUEJUNG',
            'JUNIOR',
            'JUV4 TRUCK',
            'KAIMAR',
            'KAINUO',
            'KAISER',
            'KALMAR',
            'KAMA',
            'KAMAZ',
            'KAMIKO',
            'KARGO',
            'KAROSA',
            'KASSBOHER',
            'KAWASAKI',
            'KAZENAVE',
            'KDD',
            'KEEWAY',
            'KENWORT',
            'KERAX',
            'KEWESEKI',
            'KIA',
            'KIA KITAN',
            'KIA TITAN',
            'KIAMOTORS',
            'KING',
            'KING LONG',
            'KINGO',
            'KOEGEL',
            'KOLAO',
            'KOMATSU',
            'KORANDO',
            'KORBON',
            'KRONE',
            'KRUPP',
            'KTM',
            'KUBOTA',
            'KYAMOTRE',
            'KYMCO',
            'LADA',
            'LAG',
            'LAM',
            'LAMBORGHINI',
            'LANCER',
            'LANCIA',
            'LAND DISCOVERY',
            'LAND MARK',
            'LAND ROVER',
            'LANDEDORF',
            'LANDWIN',
            'LANDWIND',
            'LANTIC',
            'LASSIRE',
            'LAVERDA',
            'LDV',
            'LEADER',
            'LEBRERO',
            'LECINEMA',
            'LECITRAILER',
            'LEGRAS',
            'LEOPARD',
            'LEOPAT',
            'LEVDEO',
            'LEVEQUE',
            'LEXUS',
            'LEYLAND',
            'LIEBHERR',
            'LIFAN',
            'LINCOLN',
            'LINGKEN',
            'LINHAI',
            'LINK - BELT',
            'LION',
            'LOCALE',
            'LOGAN',
            'LOHEAC',
            'LOHR',
            'LONCIN',
            'LONDINI 8500',
            'LONGUYON',
            'LUOJIA',
            'LYNX',
            'LYON MOTO',
            'MACHINDRA',
            'MACHINE USAGEE',
            'MACK',
            'MAFI',
            'MAGIRUS',
            'MAGNUM',
            'MAGYAR',
            'MAHINDRA',
            'MAISONEUVE',
            'MAJESTIC',
            'MALAGUTI',
            'MALINBO',
            'MAMBA',
            'MAN',
            'MANAC',
            'MANISCOPIC',
            'MANITOU',
            'MARUTI',
            'MASERATI',
            'MASSEY FERGUSSON',
            'MATRA',
            'MAYA',
            'MAZDA',
            'MD',
            'MEFCO',
            'MEGANE',
            'MEILUN',
            'MELIUM',
            'MERCEDES',
            'MESCO',
            'METACO',
            'METRO',
            'MF',
            'MG',
            'MINI',
            'MINI COOPER',
            'MINI MORIS',
            'MINJA',
            'MINSK',
            'MISTRAL',
            'MITSUBISHI',
            'MITSUZU',
            'MIXTA',
            'ML150',
            'MOBYLETTE',
            'MOL',
            'MONROC',
            'MONTENEGRO',
            'MONTI',
            'MONTSERATO',
            'MORGAN',
            'MOTO RATO',
            'MOTOBECANE',
            'MOTO-GUZZI',
            'MTR',
            'MULAG',
            'MULTI FONCTION',
            'MUSKEG',
            'MUSSO',
            'NANFANG',
            'NANY',
            'NANYA',
            'NASARA',
            'NATIONAL',
            'NETAM',
            'NETAW',
            'NEW HOLLANDE',
            'NEZER SIRENY',
            'NICOLAS',
            'NIEWIADOW',
            'NINJA',
            'NIPPON',
            'NISSAN',
            'NIVEL',
            'NOERENS',
            'NOLT MIXER TRUCK',
            'NOOTERBOOM',
            'NOUMA',
            'OFAC',
            'OLDSMOBILE',
            'ONIDA SUPER',
            'OPEL',
            'ORIGINAL',
            'ORIGINAL1',
            'OSAKI',
            'OSH KOSH',
            'OSSARHA',
            'OVER',
            'PACTON',
            'PAGGIO 50',
            'PANTERA',
            'PANTHER',
            'PARIS',
            'PART',
            'PASSERELLE',
            'PEB14',
            'PEGASO',
            'PEH',
            'PELLE CASE',
            'PENIEL',
            'PETERBILT',
            'PETIT BAW',
            'PEUGEOT',
            'PH',
            'PIAGGIO',
            'PINGUELY',
            'PISCI',
            'PLANET',
            'PLATEAU',
            'PLATEAU METAM',
            'PLYMOUTH',
            'POINTER',
            'POLARIS',
            'POMIERS',
            'PONTIAC',
            'PONY',
            'PORSCHE',
            'POTAIN',
            'POWER 50',
            'PRD FOREUSE',
            'PRESTIGE',
            'PRIMBALL',
            'PROTISS',
            'PROTON',
            'PUCH',
            'PULVERISATEUR',
            'PUSH BACK',
            'QASKI',
            'QINGOI',
            'QLINK',
            'QUINCOI',
            'RAG',
            'RAMANAZZI',
            'RAMZEY',
            'RANDON',
            'RANGE ROVER',
            'RATO',
            'REM ROLAND',
            'REMORQUE',
            'RENAULT',
            'RENDERS',
            'RICHESE',
            'RIDAL',
            'RIEJU',
            'RIMCO',
            'RISA',
            'ROADSTER SPYDER',
            'ROBUSTE',
            'ROBUSTEKAI',
            'ROBUSTE-KAISER',
            'ROCKY',
            'ROGER',
            'ROMANAZZI',
            'RORO',
            'ROTATEUR',
            'ROVER',
            'ROYAL',
            'ROYAL-ENFIELB',
            'RT FASSA',
            'RVI',
            'RYMCO',
            'S.SONIC',
            'SAAB',
            'SABENI',
            'SADLOC',
            'SAFARI',
            'SAFCA',
            'SAHA',
            'SAHARA',
            'SAHEL50Q',
            'SAKAHAN',
            'SAMA SAVANE',
            'SAMAN',
            'SAMBRON',
            'SAME',
            'SAMECO',
            'SAMESOLAR 50',
            'SAMO',
            'SAMRO',
            'SAMSUNG',
            'SAN FAN',
            'SANIL',
            'SANILI',
            'SANLG',
            'SANTURN',
            'SANY',
            'SANYA',
            'SANYA EVAME',
            'SATRI',
            'SATURNE',
            'SAVERO',
            'SAVIEM',
            'SAVVD',
            'SAVVY',
            'SCANIA',
            'SCHMITZ',
            'SCION',
            'SCOOTER',
            'SCORT',
            'SDJL',
            'SDV',
            'SEADOO',
            'SEART',
            'SEAT',
            'SENDA',
            'SERIA',
            'SETRA',
            'SGMW',
            'SGTMM',
            'SHAANXI',
            'SHACMAN',
            'SHANDONG',
            'SHANTI',
            'SHANTUI',
            'SHAWKS',
            'SHIFENG',
            'SHINERAY',
            'SHISENG CHINA',
            'SHLEV LIMITED',
            'SHUANGHUAN',
            'SHUTSU',
            'SICABO',
            'SIEVERING NUTZF',
            'SIFERCON',
            'SIFMA',
            'SIFT',
            'SILLA',
            'SIMCA',
            'SIN FAN',
            'SINALI',
            'SINKAI',
            'SINOTRUCK',
            'SIRST',
            'SIRUIS',
            'SISU',
            'SKODA',
            'SKYGO',
            'SKYWING',
            'SMART',
            'SMV',
            'SNAV',
            'SOGETRAC',
            'SONALIKA',
            'SONGYL',
            'SONIF',
            'SOUKPA',
            'SOUMAHO',
            'SOVAM',
            'SOVAMAG',
            'SOWMOTOR',
            'SPARK',
            'SPART 80',
            'SPARTTATE',
            'SPITEER',
            'SPITZER',
            'SPX',
            'SROUR',
            'SSANGYONG',
            'ST CATHERINE',
            'STAR',
            'STAS',
            'STEELBRO',
            'STEELBROS',
            'STEVENS',
            'STEYR',
            'SUBARU',
            'SUKIDA',
            'SUNNY',
            'SUNRAY',
            'SUPER',
            'SUPER 1',
            'SUPER ACCESS',
            'SUPER FASSA 1',
            'SUPER LUXE',
            'SUSTOM',
            'SUZUKI',
            'SVE',
            'SVETRUCK',
            'SWIZIO',
            'SYM',
            'TAGER LINO',
            'TAISHAND',
            'TAKEUCHI',
            'TALBOT',
            'TAMPO',
            'TANE ORIGINAL',
            'TASKERS',
            'TATA',
            'TBI',
            'TCM',
            'TD1500',
            'TEMIS',
            'TERAX',
            'TERBERG',
            'THEU',
            'THOMAS',
            'THT',
            'TIAN MA',
            'TIGER',
            'TIMBER',
            'TIPSON',
            'TISSAN',
            'TITAN',
            'TMEC CGL',
            'TOGER',
            'TOUGH',
            'TOUPIE',
            'TOYO',
            'TOYOTA',
            'TRABOSA',
            'TRACER',
            'TRACTEUR',
            'TRACTEUR RAGAGE',
            'TRAC-TOPELLE CASE 580',
            'TRACTOPELLE CAT 428C',
            'TRADE',
            'TRANSAFRIC',
            'TRAX',
            'TRILEI',
            'TRI-MOTO',
            'TRINQUEBAL',
            'TRIQUEBALLE',
            'TRIUMPH',
            'TROUILLET',
            'TRUCK',
            'TUKOI',
            'UFO',
            'UNIC',
            'UNIMOG',
            'USED',
            'VAN',
            'VAN VLIET',
            'VANHOOL',
            'VANHOUR',
            'VARMO',
            'VAUXHALL',
            'VEGARR',
            'VERONESI',
            'VESPA',
            'VGL',
            'VIBERTI',
            'VICTOR',
            'VICTORIA',
            'VITARA',
            'VMC',
            'VOGELZAN',
            'VOLKSWAGEN',
            'VOLVO',
            'WATISHAN',
            'WONDA',
            'WULING PAI',
            'WUYANG',
            'X1',
            'X-1 ACCESS',
            'X-1KTM',
            'XANIA',
            'XCMG',
            'XFWY',
            'XIAMEN',
            'XINKAI',
            'XTREME50',
            'XYNGDA',
            'YALE',
            'YAMAHA',
            'YAMAHA 50',
            'YANKEE',
            'YANMAR',
            'YAXING',
            'YINHE',
            'YITWO',
            'YOKOHAMA',
            'YORK',
            'YOROBO',
            'YUE LOONG',
            'YUEJING',
            'YUHANGJI',
            'YUTONG',
            'YWOTO',
            'ZAGNIA',
            'ZARU RZ 125-9',
            'ZARUD',
            'ZHAORUN',
            'ZHENGZHOU',
            'ZHONGYU',
            'ZHONYA',
            'ZIAJIN',
            'ZNA',
            'ZODIAC',
            'ZONGSHEN',
            'ZONTES',
            'ZORZI',
            'ZOTYE',
            'ZREMB',
            'ZUNDAPP',
            'ZX AUTO'
        ];
        $brands = [
            "Audi",
            "Buick",
            "Acura",
            "Aston Martin",
            "Bentley",
            "Bmw",
            "Cadillac",
            "Chevrolet",
            "Chrysler",
            "Citroen",
            "Daihatsu",
            "Ferrari",
            "Fiat",
            "Ford",
            "Gmc",
            "Honda",
            "Hyundai",
            "Infiniti",
            "Isuzu",
            "Jaguar",
            "Jeep",
            "Kia",
            "Lancia",
            "Land rover",
            "Lexus",
            "Lincoln",
            "Mazda",
            "Mercedes-Benz",
            "Mini",
            "Mitsubishi",
            "Nissan",
            "Oldsmobile",
            "Opel",
            "Peugeot",
            "Porsche",
            "Renault",
            "Skoda",
            "Subaru",
            "Suzuki",
            "Toyota",
            "Volkswagen",
            "Volvo",
        ];
        // Créer un nouveau tableau avec uniquement les marques de voitures et la première lettre en majuscule
        foreach ($data as $dt){
            $capitalizedBrands[] = ucfirst(strtolower($dt));
        }
        $non_populars = array_diff($capitalizedBrands, $brands);
        #print_r($non_populars);

        foreach ($brands as $brand) {
            $original_brand = $brand;
            $brand = strtolower($brand); // Convertir la marque en minuscule
            // Remplacer les accents par des caractères sans accent
            $brand = str_replace(['é', 'è', 'ê', 'ë'], 'e', $brand);
            $brand = str_replace(['ç'], 'c', $brand);
            $brand = str_replace(['à', 'â'], 'a', $brand);
            $brand = str_replace(['î', 'ï'], 'i', $brand);
            $brand = str_replace(['ô', 'ö'], 'o', $brand);
            $brand = str_replace(['ù', 'ü'], 'u', $brand);
            $brand = str_replace(['Š'], 's', $brand);

            if ($brand == 'aston martin')
                $brand = 'aston-martin';
            if ($brand == 'gmc'){
                $brand = 'gm';
            }
            if ($brand == 'land rover'){
                $brand = 'land-rover';
            }
            // Générer le chemin de l'image
            $imagePath = '/brands/' . $brand . '.png';
            if ($brand == 'daihatsu' || $brand == 'bentley' || $brand == 'cadillac' || $brand == 'isuzu'){
                $imagePath = '/brands/' . $brand . '.svg';
            }
            Brand::firstOrCreate([
                'title' => $original_brand,
                'image' => $imagePath,
                'most_used' => true,
                'status' => true
            ]);
        }
        foreach ($non_populars as $brand) {
            Brand::firstOrCreate([
                'title' => $brand,
                'most_used' => false,
                'status' => true
            ]);
        }
    }
}
